version: '3'

services:
  db:
    image: postgres
    environment:
     POSTGRES_PASSWORD: $DB_PASSWORD
     PGDATA: /var/lib/postgresql/data/pgdata
     POSTGRES_DB: $DB_NAME
     POSTGRES_USER: $DB_USER
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5


  electronic_shop:
    build: .
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/electronic_shop_app
    depends_on:
      db:
        condition: service_healthy